# Site settings
author: dauntless-media-7189
title: 
header-img: img/home-bg.png
email: kieuha2212@gmail.com
copyright_name: dauntless-media-7189
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kieuha

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
